name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:  
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1   
    - name: Build
      run: cargo build --verbose
  build_float:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1   
    - name: Build Float
      run: cargo build --verbose --features float 