name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:    
  build:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3                 
      - name: Update
        run: rustup update
      - name: Build Float
        run: cargo build --verbose 
  build_float:      
    runs-on: ubuntu-latest   
    steps:
      - uses: actions/checkout@v3   
      - name: Update
        run: rustup update
      - name: Build Float
        run: cargo build --verbose --features float 
  build_parallel:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3            
      - name: Update
        run: rustup update
      - name: Build Float
        run: cargo build --verbose --features parallel 
  
  build_quick_inv:   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3            
      - name: Update
        run: rustup update
      - name: Build Float
        run: cargo build --verbose --features quick_inv_sqrt 