name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:  
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1   
    - name: Build
      run: cargo build --verbose
  build_float:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1   
    - name: Build Float
      run: cargo build --verbose --features float 
  build_parallel:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1   
    - name: Build Float
      run: cargo build --verbose --features parallel 
  build_textures:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1   
    - name: Build Float
      run: cargo build --verbose --features textures 
  build_quick_inv:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1   
    - name: Build Float
      run: cargo build --verbose --features quick_inv_sqrt 