name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:  
  toolchain:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1   
    - name: Update
      run: rustup update
    - name: Set Toolchain
      run: rustup default nightly
  build:  
    needs: toolchain  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1   
    - name: Build Float
      run: cargo build --verbose 
  build_float:  
    needs: toolchain  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1   
    - name: Build Float
      run: cargo build --verbose --features float 
  build_parallel:    
    needs: toolchain  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1   
    - name: Build Float
      run: cargo build --verbose --features parallel 
  build_textures:    
    needs: toolchain  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1   
    - name: Build Float
      run: cargo build --verbose --features textures 
  build_quick_inv:  
    needs: toolchain    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1   
    - name: Build Float
      run: cargo build --verbose --features quick_inv_sqrt 