on:
  push:
    branches: [master]
  pull_request:
name: coverage
jobs:
  toolchain:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1  
      - name: Update
        run: rustup update 
      - name: Set Toolchain
        run: rustup default nightly
  test:
    needs: toolchain
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v2
      - name: Generate code coverage
        run: |
          cargo tarpaulin --verbose --timeout 600 --out Xml
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          