on: push
name: Clippy check
jobs:
  toolchain:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1   
      - name: Set Toolchain
        run: rustup default nightly
  clippy_check:
    needs: toolchain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}          