on: push
name: Clippy check
jobs:  
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: install clippy
        run: rustup component add clippy      
      - name: Update
        run: rustup update
      - name: Run Clippy
        run: cargo clippy
