name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:    
  test:    
    runs-on: ubuntu-latest         
    steps:
      - uses: actions/checkout@v1   
      - name: Set Toolchain
        run: rustup default nightly    
      - name: Update
        run: rustup update
      - name: Run tests
        run: cargo test --verbose    
  test_float:    
    runs-on: ubuntu-latest         
    steps:
      - uses: actions/checkout@v1   
      - name: Set Toolchain
        run: rustup default nightly    
      - name: Update
        run: rustup update
      - name: Run tests
        run: cargo test --features float --verbose    
  test_parallel:
    runs-on: ubuntu-latest         
    steps:
      - uses: actions/checkout@v1   
      - name: Set Toolchain
        run: rustup default nightly    
      - name: Update
        run: rustup update
      - name: Run tests
        run: cargo test --features parallel --verbose    
  test_textures:
    runs-on: ubuntu-latest   
    steps:      
      - uses: actions/checkout@v1   
      - name: Set Toolchain
        run: rustup default nightly    
      - name: Update
        run: rustup update
      - name: Run tests
        run: cargo test --features textures --verbose   
  test_quick_inv_sqrt:
    runs-on: ubuntu-latest    
    steps:     
      - uses: actions/checkout@v1   
      - name: Set Toolchain
        run: rustup default nightly    
      - name: Update
        run: rustup update
      - name: Run tests
        run: cargo test --features quick_inv_sqrt --verbose    
        