name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:  
  toolchain:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1   
    - name: Set Toolchain
      run: rustup default nightly
  test:
    needs: toolchain
    runs-on: ubuntu-latest         
    - uses: actions/checkout@v1   
    - name: Run tests
      run: cargo test --verbose    
  test_float:
    needs: toolchain
    runs-on: ubuntu-latest         
    - uses: actions/checkout@v1   
    - name: Run tests
      run: cargo test --features float --verbose    
  test_parallel:
    needs: toolchain
    runs-on: ubuntu-latest         
    - uses: actions/checkout@v1   
    - name: Run tests
      run: cargo test --features parallel --verbose    
  test_textures:
    needs: toolchain
    runs-on: ubuntu-latest         
    - uses: actions/checkout@v1   
    - name: Run tests
      run: cargo test --features textures --verbose   
  test_quick_inv_sqrt:
    needs: toolchain
    runs-on: ubuntu-latest         
    - uses: actions/checkout@v1   
    - name: Run tests
      run: cargo test --features quick_inv_sqrt --verbose    
        