name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:  
  test:
    runs-on: ubuntu-latest     
    steps:
    - uses: taiki-e/install-action@cargo-hack 
    - name: Run tests
      run: cargo hack test --feature-powerset --verbose     
  
    # - uses: actions/checkout@v1   
    # - name: Run tests
    #   run: cargo test --verbose    
    # - name: Run tests textures
    #   run: cargo test --features textures --verbose     
    # - name: Run tests float
    #   run: cargo test --features float --verbose     
    # - name: Run tests parallel
    #   run: cargo test --features parallel --verbose     
    # - name: Run tests all
    #   run: cargo test --all-features --verbose     
  